# Generated by Django 4.2.10 on 2025-04-20 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthcheckcard",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="teamsummary",
            options={"ordering": ["-session__date"]},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcheckcard",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="healthcheckcard",
            name="icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="healthcheckcard",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="session",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(default="Health Check Session", max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamsummary",
            name="amber_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamsummary",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="teamsummary",
            name="green_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamsummary",
            name="red_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="teamsummary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="vote",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="teamsummary",
            unique_together={("team", "card", "session")},
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "card", "session")},
        ),
        migrations.CreateModel(
            name="DepartmentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_vote",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("amber", "Amber"),
                            ("red", "Red"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "progress_summary",
                    models.CharField(
                        choices=[
                            ("better", "Better"),
                            ("same", "Same"),
                            ("worse", "Worse"),
                        ],
                        max_length=6,
                    ),
                ),
                ("green_percentage", models.FloatField(default=0)),
                ("amber_percentage", models.FloatField(default=0)),
                ("red_percentage", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.healthcheckcard",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.session"
                    ),
                ),
            ],
            options={
                "ordering": ["-session__date"],
                "unique_together": {("department", "card", "session")},
            },
        ),
    ]
